# Generated by Django 4.0.3 on 2022-05-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAlinhamentoestrategico',
            fields=[
                ('id_alinhamentoestrategico', models.IntegerField(db_column='Id_AlinhamentoEstrategico', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_alinhamentoestrategico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCadastrodemandas',
            fields=[
                ('id_cadastrodemandas', models.AutoField(db_column='Id_CadastroDemandas', primary_key=True, serialize=False)),
                ('cad_codigodemanda', models.IntegerField(db_column='cad_CodigoDemanda')),
                ('cad_descricao', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='cad_Descricao', max_length=255, null=True)),
                ('cad_observacao', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='cad_Observacao', max_length=1000, null=True)),
                ('cad_datainclusao', models.DateField(blank=True, db_column='cad_DataInclusao', null=True)),
                ('cad_status', models.IntegerField(blank=True, db_column='cad_Status', null=True)),
                ('cad_especiedespesa', models.CharField(blank=True, db_collation='utf8mb4_general_ci', db_column='cad_EspecieDespesa', max_length=2500, null=True)),
            ],
            options={
                'db_table': 'tbl_cadastrodemandas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCoordenadoressetoriais',
            fields=[
                ('cso_codigo', models.CharField(db_column='cso_Codigo', max_length=8, primary_key=True, serialize=False)),
                ('cso_nome', models.CharField(db_column='cso_Nome', max_length=255)),
                ('cso_areatematica', models.CharField(blank=True, db_column='cso_AreaTematica', max_length=255, null=True)),
                ('cso_datainclusao', models.DateField(blank=True, db_column='cso_DataInclusao', null=True)),
                ('cso_status', models.IntegerField(blank=True, db_column='cso_Status', null=True)),
                ('cso_instrumentolegal', models.CharField(blank=True, db_column='cso_InstrumentoLegal', max_length=255, null=True)),
                ('cso_ordenadordespesa', models.CharField(blank=True, db_column='cso_OrdenadorDespesa', max_length=11, null=True)),
            ],
            options={
                'db_table': 'tbl_coordenadoressetoriais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDisponibilidade',
            fields=[
                ('id_disponibilidade', models.AutoField(db_column='Id_Disponibilidade', primary_key=True, serialize=False)),
                ('dsp_status', models.CharField(blank=True, db_column='dsp_Status', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_disponibilidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEspeciedisponibilidade',
            fields=[
                ('id_especiedisponibilidade', models.AutoField(db_column='Id_EspecieDisponibilidade', primary_key=True, serialize=False)),
                ('esd_discriminacao', models.CharField(blank=True, db_column='esd_Discriminacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_especiedisponibilidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblEstrategia',
            fields=[
                ('id_estrategia', models.AutoField(db_column='Id_Estrategia', primary_key=True, serialize=False)),
                ('est_codigo', models.CharField(db_column='est_Codigo', max_length=6)),
                ('est_descricao', models.CharField(db_column='est_Descricao', max_length=250)),
                ('est_status', models.IntegerField(blank=True, db_column='est_Status', null=True)),
                ('est_observacao', models.CharField(blank=True, db_column='est_Observacao', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tbl_estrategia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfcreditosorcamentarios',
            fields=[
                ('id_fcdfcreditosorcamentarios', models.IntegerField(db_column='Id_FCDFCreditosOrcamentarios', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_fcdfcreditosorcamentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfempenho',
            fields=[
                ('emf_codigo', models.CharField(db_column='emf_Codigo', max_length=23, primary_key=True, serialize=False)),
                ('emf_descricao', models.CharField(db_column='emf_Descricao', max_length=1000)),
                ('emf_numeroprocesso', models.CharField(blank=True, db_column='emf_NumeroProcesso', max_length=23, null=True)),
                ('emf_dataemissao', models.DateField(blank=True, db_column='emf_DataEmissao', null=True)),
                ('emf_esfera', models.CharField(blank=True, db_column='emf_Esfera', max_length=23, null=True)),
                ('emf_fonte', models.CharField(blank=True, db_column='emf_Fonte', max_length=10, null=True)),
                ('emf_programatrabalhoresumido', models.CharField(blank=True, db_column='emf_ProgramaTrabalhoResumido', max_length=10, null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfempenho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfitemempenho',
            fields=[
                ('id_fcdfitemempenho', models.AutoField(db_column='Id_FCDFItemEmpenho', primary_key=True, serialize=False)),
                ('itf_descricao', models.CharField(db_column='itf_Descricao', max_length=100)),
                ('itf_operacao', models.CharField(db_column='itf_Operacao', max_length=50)),
                ('itf_quantidade', models.DecimalField(blank=True, db_column='itf_Quantidade', decimal_places=2, max_digits=15, null=True)),
                ('itf_valor', models.DecimalField(blank=True, db_column='itf_Valor', decimal_places=2, max_digits=15, null=True)),
                ('itf_data', models.DateField(blank=True, db_column='itf_Data', null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfitemempenho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfitemliquidacao',
            fields=[
                ('id_fcdfitemliquidacao', models.IntegerField(db_column='Id_FCDFItemLiquidacao', primary_key=True, serialize=False)),
                ('lig_quantidade', models.DecimalField(blank=True, db_column='lig_Quantidade', decimal_places=2, max_digits=15, null=True)),
                ('lig_valor', models.DecimalField(blank=True, db_column='lig_Valor', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfitemliquidacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfitempagamento',
            fields=[
                ('id_fcdfitempagamento', models.IntegerField(db_column='Id_FCDFItemPagamento', primary_key=True, serialize=False)),
                ('pgf_quantidade', models.DecimalField(blank=True, db_column='pgf_Quantidade', decimal_places=2, max_digits=15, null=True)),
                ('pgf_vavlor', models.DecimalField(blank=True, db_column='pgf_Vavlor', decimal_places=2, max_digits=15, null=True)),
                ('pgf_data', models.DateField(blank=True, db_column='pgf_Data', null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfitempagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfnaturezadespesadetalhada',
            fields=[
                ('nfc_codigo', models.CharField(db_column='nfc_Codigo', max_length=8, primary_key=True, serialize=False)),
                ('nfc_descricao', models.CharField(blank=True, db_column='nfc_Descricao', max_length=255, null=True)),
                ('nfc_categoriaeconomica', models.CharField(blank=True, db_column='nfc_CategoriaEconomica', max_length=3, null=True)),
                ('nfc_grupodespesa', models.CharField(blank=True, db_column='nfc_GrupoDespesa', max_length=3, null=True)),
                ('nfc_modalidadeaplicacao', models.CharField(blank=True, db_column='nfc_ModalidadeAplicacao', max_length=3, null=True)),
                ('nfc_elementodespesa', models.CharField(blank=True, db_column='nfc_ElementoDespesa', max_length=3, null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfnaturezadespesadetalhada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfplanointernoorcamento',
            fields=[
                ('id_fcdfplanointerno', models.AutoField(db_column='Id_FCDFPlanoInterno', primary_key=True, serialize=False)),
                ('pif_justificativa', models.CharField(blank=True, db_column='pif_Justificativa', max_length=255, null=True)),
                ('pif_unidadeorcamentaria', models.CharField(blank=True, db_column='pif_UnidadeOrcamentaria', max_length=6, null=True)),
                ('pif_fonte', models.CharField(blank=True, db_column='pif_Fonte', max_length=3, null=True)),
                ('pif_programatrabalho', models.CharField(blank=True, db_column='pif_ProgramaTrabalho', max_length=17, null=True)),
                ('pif_quantidade', models.IntegerField(blank=True, db_column='pif_Quantidade', null=True)),
                ('pif_valor', models.DecimalField(blank=True, db_column='pif_Valor', decimal_places=2, max_digits=15, null=True)),
                ('pif_exercicio', models.TextField(blank=True, db_column='pif_Exercicio', null=True)),
                ('pif_observacao', models.CharField(blank=True, db_column='pif_Observacao', max_length=1000, null=True)),
                ('pif_data', models.DateField(db_column='pif_Data')),
            ],
            options={
                'db_table': 'tbl_fcdfplanointernoorcamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfproposta',
            fields=[
                ('id_fcdfproposta', models.AutoField(db_column='Id_FCDFProposta', primary_key=True, serialize=False)),
                ('prf_justificativa', models.CharField(blank=True, db_column='prf_Justificativa', max_length=255, null=True)),
                ('prf_quantidade', models.IntegerField(blank=True, db_column='prf_Quantidade', null=True)),
                ('prf_valor', models.DecimalField(blank=True, db_column='prf_Valor', decimal_places=2, max_digits=15, null=True)),
                ('prf_fonte', models.CharField(blank=True, db_column='prf_Fonte', max_length=3, null=True)),
                ('prf_programatrabalho', models.CharField(blank=True, db_column='prf_ProgramaTrabalho', max_length=45, null=True)),
                ('prf_exercicio', models.TextField(blank=True, db_column='prf_Exercicio', null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfproposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfquadrodetalhamentodespesa',
            fields=[
                ('id_gdfquadrodetalhamentodespesa', models.AutoField(db_column='id_GDFQuadroDetalhamentoDespesa', primary_key=True, serialize=False)),
                ('qdf_dataemissao', models.DateField(blank=True, db_column='qdf_DataEmissao', null=True)),
                ('qdf_exerciciofinanceiro', models.TextField(blank=True, db_column='qdf_ExercicioFinanceiro', null=True)),
                ('qdf_funcao', models.CharField(blank=True, db_column='qdf_Funcao', max_length=45, null=True)),
                ('qdf_subfuncao', models.CharField(blank=True, db_column='qdf_Subfuncao', max_length=45, null=True)),
                ('qdf_programa', models.CharField(blank=True, db_column='qdf_Programa', max_length=45, null=True)),
                ('qdf_acao', models.CharField(blank=True, db_column='qdf_Acao', max_length=45, null=True)),
                ('qdf_subitulo', models.CharField(blank=True, db_column='qdf_Subitulo', max_length=45, null=True)),
                ('qdf_planoorcamentario', models.CharField(blank=True, db_column='qdf_PlanoOrcamentario', max_length=45, null=True)),
                ('qdf_fonte', models.CharField(blank=True, db_column='qdf_Fonte', max_length=45, null=True)),
                ('qdf_naturezadespesa', models.CharField(blank=True, db_column='qdf_NaturezaDespesa', max_length=45, null=True)),
                ('qdf_lei', models.DecimalField(blank=True, db_column='qdf_Lei', decimal_places=2, max_digits=15, null=True)),
                ('qdf_dotacaoinicial', models.DecimalField(blank=True, db_column='qdf_DotacaoInicial', decimal_places=2, max_digits=15, null=True)),
                ('qdf_dotacaoautorizada', models.DecimalField(blank=True, db_column='qdf_DotacaoAutorizada', decimal_places=2, max_digits=15, null=True)),
                ('qdf_despesaautorizada', models.DecimalField(blank=True, db_column='qdf_DespesaAutorizada', decimal_places=2, max_digits=15, null=True)),
                ('qdf_empenhado', models.DecimalField(blank=True, db_column='qdf_Empenhado', decimal_places=2, max_digits=15, null=True)),
                ('qdf_liquidado', models.DecimalField(blank=True, db_column='qdf_Liquidado', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_fcdfquadrodetalhamentodespesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblFcdfremanejamento',
            fields=[
                ('id_fcdfremanejamentos', models.AutoField(db_column='Id_FCDFRemanejamentos', primary_key=True, serialize=False)),
                ('ref_descricao', models.CharField(blank=True, db_column='ref_Descricao', max_length=1000, null=True)),
                ('ref_especieremanejamento', models.CharField(db_column='ref_EspecieRemanejamento', max_length=13)),
                ('ref_quantidade', models.IntegerField(blank=True, db_column='ref_Quantidade', null=True)),
                ('ref_valor', models.DecimalField(blank=True, db_column='ref_Valor', decimal_places=2, max_digits=15, null=True)),
                ('ref_data', models.DateField(db_column='ref_Data')),
            ],
            options={
                'db_table': 'tbl_fcdfremanejamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfempenho',
            fields=[
                ('emg_codigo', models.CharField(db_column='emg_Codigo', max_length=23, primary_key=True, serialize=False)),
                ('emg_descricao', models.CharField(db_column='emg_Descricao', max_length=1000)),
                ('emf_numeroprocesso', models.CharField(blank=True, db_column='emf_NumeroProcesso', max_length=23, null=True)),
                ('emf_dataemissao', models.DateField(blank=True, db_column='emf_DataEmissao', null=True)),
            ],
            options={
                'db_table': 'tbl_gdfempenho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfitemempenho',
            fields=[
                ('id_gdfitemempenho', models.AutoField(db_column='Id_GDFItemEmpenho', primary_key=True, serialize=False)),
                ('itf_descricao', models.CharField(db_column='itf_Descricao', max_length=100)),
                ('itf_operacao', models.CharField(db_column='itf_Operacao', max_length=50)),
                ('itf_quantidade', models.DecimalField(blank=True, db_column='itf_Quantidade', decimal_places=2, max_digits=15, null=True)),
                ('itg_valor', models.DecimalField(blank=True, db_column='itg_Valor', decimal_places=2, max_digits=15, null=True)),
                ('itg_data', models.DateField(blank=True, db_column='itg_Data', null=True)),
            ],
            options={
                'db_table': 'tbl_gdfitemempenho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfitemliquidacao',
            fields=[
                ('id_gdfitemliquidacao', models.IntegerField(db_column='Id_GDFItemLiquidacao', primary_key=True, serialize=False)),
                ('lig_qantidade', models.DecimalField(blank=True, db_column='lig_Qantidade', decimal_places=2, max_digits=15, null=True)),
                ('lig_valor', models.DecimalField(blank=True, db_column='lig_Valor', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_gdfitemliquidacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfitempagamento',
            fields=[
                ('id_gdfitempagamento', models.IntegerField(db_column='Id_GDFItemPagamento', primary_key=True, serialize=False)),
                ('pag_qantidade', models.DecimalField(blank=True, db_column='pag_Qantidade', decimal_places=2, max_digits=15, null=True)),
                ('pag_valor', models.DecimalField(blank=True, db_column='pag_Valor', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_gdfitempagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfnaturezadespesadetalhada',
            fields=[
                ('ndf_codigo', models.CharField(db_column='ndf_Codigo', max_length=8, primary_key=True, serialize=False)),
                ('ndf_descricao', models.CharField(db_column='ndf_Descricao', max_length=255)),
                ('ndf_categoriaeconomica', models.CharField(db_column='ndf_CategoriaEconomica', max_length=3)),
                ('ndf_grupodespesa', models.CharField(db_column='ndf_GrupoDespesa', max_length=3)),
                ('ndf_modalidadeaplicacao', models.CharField(db_column='ndf_ModalidadeAplicacao', max_length=2)),
                ('ndf_elementodespesa', models.CharField(blank=True, db_column='ndf_ElementoDespesa', max_length=3, null=True)),
            ],
            options={
                'db_table': 'tbl_gdfnaturezadespesadetalhada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfpiocreditosorcamentarios',
            fields=[
                ('id_gdfpiocreditosorcamentarios', models.IntegerField(db_column='Id_GDFPIOCreditosOrcamentarios', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_gdfpiocreditosorcamentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfplanointernoorcamento',
            fields=[
                ('id_gdfplanointernoorcamento', models.AutoField(db_column='Id_GDFPlanoInternoOrcamento', primary_key=True, serialize=False)),
                ('pig_quantidade', models.IntegerField(blank=True, db_column='pig_Quantidade', null=True)),
                ('pig_valor', models.DecimalField(blank=True, db_column='pig_Valor', decimal_places=2, max_digits=15, null=True)),
                ('pig_data', models.DateField(db_column='pig_Data')),
                ('pig_observacoes', models.CharField(blank=True, db_column='pig_Observacoes', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tbl_gdfplanointernoorcamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfproposta',
            fields=[
                ('id_gdfproposta', models.AutoField(db_column='Id_GDFProposta', primary_key=True, serialize=False)),
                ('prg_justificativa', models.CharField(blank=True, db_column='prg_Justificativa', max_length=255, null=True)),
                ('prg_quantidade', models.IntegerField(blank=True, db_column='prg_Quantidade', null=True)),
                ('prg_valor', models.DecimalField(blank=True, db_column='prg_Valor', decimal_places=2, max_digits=15, null=True)),
                ('prg_unidadeorcamentaria', models.CharField(blank=True, db_column='prg_UnidadeOrcamentaria', max_length=5, null=True)),
                ('prg_fonte', models.CharField(blank=True, db_column='prg_Fonte', max_length=9, null=True)),
                ('prg_identificadoruso', models.IntegerField(blank=True, db_column='prg_IdentificadorUso', null=True)),
                ('prg_programatrabalho', models.CharField(blank=True, db_column='prg_ProgramaTrabalho', max_length=17, null=True)),
                ('prg_exercicio', models.TextField(blank=True, db_column='prg_Exercicio', null=True)),
            ],
            options={
                'db_table': 'tbl_gdfproposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfquadrodetalhamentodespesa',
            fields=[
                ('id_gdfquadrodetalhamentodespesa', models.AutoField(db_column='id_GDFQuadroDetalhamentoDespesa', primary_key=True, serialize=False)),
                ('qdg_exerciciofinanceiro', models.TextField(blank=True, db_column='qdg_ExercicioFinanceiro', null=True)),
                ('qdg_unidadeorcamentaria', models.IntegerField(blank=True, db_column='qdg_UnidadeOrcamentaria', null=True)),
                ('qdg_mesreferencia', models.CharField(blank=True, db_collation='latin1_swedish_ci', db_column='qdg_MesReferencia', max_length=11, null=True)),
                ('qdg_dataemissao', models.DateField(blank=True, db_column='qdg_DataEmissao', null=True)),
                ('qdg_esfera', models.IntegerField(blank=True, db_column='qdg_Esfera', null=True)),
                ('qdg_naturezadespesa', models.IntegerField(blank=True, db_column='qdg_NaturezaDespesa', null=True)),
                ('qdg_fonte', models.IntegerField(blank=True, db_column='qdg_Fonte', null=True)),
                ('qdg_identificadoruso', models.IntegerField(blank=True, db_column='qdg_IdentificadorUso', null=True)),
                ('qdg_programatrabalho', models.CharField(blank=True, db_column='qdg_ProgramaTrabalho', max_length=17, null=True)),
                ('qdg_lei', models.DecimalField(blank=True, db_column='qdg_Lei', decimal_places=2, max_digits=15, null=True)),
                ('qdg_alteracao', models.DecimalField(blank=True, db_column='qdg_Alteracao', decimal_places=2, max_digits=15, null=True)),
                ('qdg_contingenciado', models.DecimalField(blank=True, db_column='qdg_Contingenciado', decimal_places=2, max_digits=15, null=True)),
                ('qdg_cota', models.DecimalField(blank=True, db_column='qdg_Cota', decimal_places=2, max_digits=15, null=True)),
                ('qdg_bloqueado', models.DecimalField(blank=True, db_column='qdg_Bloqueado', decimal_places=2, max_digits=15, null=True)),
                ('qdg_despesaautorizada', models.DecimalField(blank=True, db_column='qdg_DespesaAutorizada', decimal_places=2, max_digits=15, null=True)),
                ('qdg_empenhado', models.DecimalField(blank=True, db_column='qdg_Empenhado', decimal_places=2, max_digits=15, null=True)),
                ('qdg_disponivel', models.DecimalField(blank=True, db_column='qdg_Disponivel', decimal_places=2, max_digits=15, null=True)),
                ('qdg_liquidado', models.DecimalField(blank=True, db_column='qdg_Liquidado', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_gdfquadrodetalhamentodespesa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblGdfremanejamento',
            fields=[
                ('id_gdfremanejamentos', models.AutoField(db_column='Id_GDFRemanejamentos', primary_key=True, serialize=False)),
                ('reg_descricao', models.CharField(blank=True, db_column='reg_Descricao', max_length=1000, null=True)),
                ('reg_especieremanejamento', models.CharField(db_column='reg_EspecieRemanejamento', max_length=13)),
                ('reg_quantidade', models.IntegerField(blank=True, db_column='reg_Quantidade', null=True)),
                ('reg_valor', models.DecimalField(blank=True, db_column='reg_Valor', decimal_places=2, max_digits=15, null=True)),
                ('reg_data', models.DateField(db_column='reg_Data')),
            ],
            options={
                'db_table': 'tbl_gdfremanejamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblIniciativaestrategica',
            fields=[
                ('id_iniciativaestrategica', models.AutoField(db_column='Id_IniciativaEstrategica', primary_key=True, serialize=False)),
                ('ini_codigo', models.CharField(db_column='ini_Codigo', max_length=9)),
                ('ini_descricao', models.CharField(db_column='ini_Descricao', max_length=250)),
                ('ini_status', models.IntegerField(blank=True, db_column='ini_Status', null=True)),
                ('ini_observacao', models.CharField(blank=True, db_column='ini_Observacao', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tbl_iniciativaestrategica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblItemaquisicaoservico',
            fields=[
                ('id_itemaqusicaoservico', models.IntegerField(db_column='Id_ItemAqusicaoServico', primary_key=True, serialize=False)),
                ('ias_codigo', models.IntegerField(blank=True, db_column='ias_Codigo', null=True)),
                ('ias_descricao', models.CharField(blank=True, db_column='ias_Descricao', max_length=500, null=True)),
                ('ias_quantidade', models.IntegerField(blank=True, db_column='ias_Quantidade', null=True)),
                ('ias_unidademedida', models.CharField(blank=True, db_column='ias_UnidadeMedida', max_length=45, null=True)),
                ('ias_valor', models.DecimalField(blank=True, db_column='ias_Valor', decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'tbl_itemaquisicaoservico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblObjetivo',
            fields=[
                ('id_objetivo', models.AutoField(db_column='Id_Objetivo', primary_key=True, serialize=False)),
                ('obj_codigo', models.CharField(db_column='obj_Codigo', max_length=3)),
                ('obj_descricao', models.CharField(db_column='obj_Descricao', max_length=250)),
                ('obj_status', models.IntegerField(blank=True, db_column='obj_Status', null=True)),
                ('obj_observacao', models.CharField(blank=True, db_column='obj_Observacao', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tbl_objetivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPeriodicidade',
            fields=[
                ('id_periodicidade', models.IntegerField(db_column='Id_Periodicidade', primary_key=True, serialize=False)),
                ('per_descricao', models.CharField(db_column='per_Descricao', max_length=45)),
            ],
            options={
                'db_table': 'tbl_periodicidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPrevisaofaseexecucao',
            fields=[
                ('id_previsaofaseexecucao', models.IntegerField(db_column='Id_PrevisaoFaseExecucao', primary_key=True, serialize=False)),
                ('fse_fase', models.CharField(blank=True, db_column='fse_Fase', max_length=45, null=True)),
                ('fse_inicio', models.DateField(blank=True, db_column='fse_Inicio', null=True)),
                ('fse_termino', models.DateField(blank=True, db_column='fse_Termino', null=True)),
            ],
            options={
                'db_table': 'tbl_previsaofaseexecucao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProcessoaquisicaoservico',
            fields=[
                ('id_processoaquisicaoservico', models.CharField(db_column='Id_ProcessoAquisicaoServico', max_length=19, primary_key=True, serialize=False)),
                ('pas_responsavel', models.CharField(blank=True, db_column='pas_Responsavel', max_length=45, null=True)),
                ('pas_descricao', models.CharField(blank=True, db_column='pas_Descricao', max_length=500, null=True)),
            ],
            options={
                'db_table': 'tbl_processoaquisicaoservico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblProdutounidade',
            fields=[
                ('pdu_codigo', models.IntegerField(db_column='pdu_Codigo', primary_key=True, serialize=False)),
                ('pdu_especificacao', models.CharField(blank=True, db_column='pdu_Especificacao', max_length=45, null=True)),
                ('pdu_unidademedida', models.CharField(blank=True, db_column='pdu_UnidadeMedida', max_length=45, null=True)),
            ],
            options={
                'db_table': 'tbl_produtounidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPropostasetorial',
            fields=[
                ('id_propostasetorial', models.AutoField(db_column='Id_PropostaSetorial', primary_key=True, serialize=False)),
                ('pps_justificativa', models.CharField(blank=True, db_column='pps_Justificativa', max_length=255, null=True)),
                ('pps_quantidade', models.IntegerField(blank=True, db_column='pps_Quantidade', null=True)),
                ('pps_valor', models.DecimalField(blank=True, db_column='pps_Valor', decimal_places=2, max_digits=15, null=True)),
                ('pps_observacao', models.CharField(blank=True, db_column='pps_Observacao', max_length=1000, null=True)),
                ('pps_unidadedemandante', models.CharField(blank=True, db_column='pps_UnidadeDemandante', max_length=255, null=True)),
                ('pps_exercicio', models.TextField(db_column='pps_Exercicio')),
                ('pps_status', models.IntegerField(blank=True, db_column='pps_Status', null=True)),
                ('pps_data', models.DateField(db_column='pps_Data')),
            ],
            options={
                'db_table': 'tbl_propostasetorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='viw_fcdfqdd2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emissao', models.DateField(blank=True, db_column='Emissão', null=True)),
                ('ano', models.TextField(blank=True, db_column='Ano', null=True)),
                ('ordendador', models.CharField(blank=True, db_column='Ordenador deDespesa', max_length=36, null=True)),
                ('Programa', models.CharField(blank=True, db_column='Programa de Trabalho', max_length=21, null=True)),
                ('Plano', models.CharField(blank=True, db_column='Plano Orcamentário', max_length=144, null=True)),
                ('Fonte', models.CharField(blank=True, db_column='Fonte', max_length=150, null=True)),
                ('Grupo', models.CharField(blank=True, db_column='Grupo de Despesa', max_length=25, null=True)),
                ('Lei', models.DecimalField(blank=True, db_column='Lei', decimal_places=2, max_digits=37, null=True)),
                ('DotacaoInicial', models.DecimalField(blank=True, db_column='Dotação Inicial', decimal_places=2, max_digits=38, null=True)),
                ('DotacaoAtual', models.DecimalField(blank=True, db_column='Dotação Atual', decimal_places=2, max_digits=38, null=True)),
                ('Empenhado', models.DecimalField(blank=True, db_column='Empenhado', decimal_places=2, max_digits=37, null=True)),
                ('Liquidado', models.DecimalField(blank=True, db_column='Liquidado', decimal_places=2, max_digits=37, null=True)),
                ('Pago', models.DecimalField(blank=True, db_column='Pago', decimal_places=2, max_digits=37, null=True)),
            ],
            options={
                'db_table': 'viw_qddfcdf2',
                'managed': False,
            },
        ),
    ]
