# Generated by Django 4.0.3 on 2022-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siofapp', '0002_tblplanointernoorcamento_viw_qddfcdf2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='viw_qddGdf',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Exercicio', models.TextField(db_column='Exercicio')),
                ('Mes', models.TextField(db_column='Mes')),
                ('Emissao', models.DateField(db_column='Emissao')),
                ('Ordenador', models.CharField(blank=True, db_column='Departamento', max_length=36, null=True)),
                ('Fonte', models.CharField(blank=True, db_column='Fonte', max_length=36, null=True)),
                ('Grupo', models.CharField(blank=True, db_column='Grupo', max_length=36, null=True)),
                ('Lei', models.DecimalField(blank=True, db_column='Lei', decimal_places=2, max_digits=37, null=True)),
                ('Alteracao', models.DecimalField(blank=True, db_column='Altarecao', decimal_places=2, max_digits=37, null=True)),
                ('Autorizada', models.DecimalField(blank=True, db_column='Autorizada', decimal_places=2, max_digits=37, null=True)),
                ('Empenhado', models.DecimalField(blank=True, db_column='Empenhado', decimal_places=2, max_digits=37, null=True)),
                ('Liquidado', models.DecimalField(blank=True, db_column='Liquidado', decimal_places=2, max_digits=37, null=True)),
            ],
            options={
                'db_table': 'viw_qddGdf',
                'managed': False,
            },
        ),
    ]
